dependencies:
  - OpenZeppelin/openzeppelin-contracts@4.2.0   
# https://github.com/OpenZeppelin/openzeppelin-contracts (current verion as of 15Apr22 is 4.5.0)
  - smartcontractkit/chainlink-brownie-contracts@0.2.1
# https://github.com/smartcontractkit/chainlink-brownie-contracts

compiler:
  solc:
    remappings:
      - '@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.2.0'
      - '@chainlink=smartcontractkit/chainlink-brownie-contracts@0.2.1'
dev_deployment_artifacts: True
networks:
  development:
    verify: False
  ganache-local:
    verify: False
  ganache:
    verify: False
  rinkeby:
    verify: True 
    link_token: "0x01BE23585060835E02B77ef475b0Cc51aA1e0709"
    #https://docs.chain.link/docs/ethereum-addresses/#Rinkeby%20Testnet
    eth_usd_price_feed: "0x8A753747A1Fa494EC906cE90E9f37563A8AF630e"
    dai_usd_price_feed: "0x2bA49Aaa16E6afD2a993473cfB70Fa8559B523cF"
    weth_token: '0xc778417E063141139Fce010982780140Aa0cD5Ab'
    fau_token: '0xFab46E002BbF0b4509813474841E0716E6730136'
  kovan:
    verify: True
    link_token: "0xa36085F69e2889c224210F603D836748e7dC0088"
    #https://kovan.etherscan.io/address/0xd0a1e359811322d97991e03f863a0c30c2cf029c
    weth_token: '0xd0a1e359811322d97991e03f863a0c30c2cf029c'
    #https://kovan.etherscan.io/address/0xFab46E002BbF0b4509813474841E0716E6730136
    fau_token: '0xFab46E002BbF0b4509813474841E0716E6730136'
    #https://docs.chain.link/docs/ethereum-addresses/#Kovan%20Testnet
    dai_usd_price_feed: '0x777A68032a88E5A84678A77Af2CD65A7b3c0775a'
    eth_usd_price_feed: '0x9326BFA02ADD2366b30bacB125260Af641031331'
wallets:
  from_key: ${PRIVATE_KEY}
